# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
a = np.array([9,5,2,7,6])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(a))

[2 5 6 7 9]


# Problem 2

In [20]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np
a = np.array([10,15,30,45,60])
print(a)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
b = np.arange(5,16)
print(b)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c = np.arange(50,101,5)
print(c)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
d = np.zeros(10)
print(d)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
e = np.ones(10)
print(e)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
f = np.linspace(0,100,5)
print(f)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
g = np.random.randint(10,30,5)
print(g)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
h = np.random.normal(-1,1,10)
print(h)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
i = np.random.randint(10,50,[3,5])
print(i)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(np.sum(i, axis=0))
print(np.sum(i, axis=1))
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(i.max())
print(i.min())
print(np.average(i))
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
index = np.argmax(i)
satir , sutun = np.unravel_index(index, i.shape)
print(f"[{satir}] [{sutun}]")
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
j = np.arange(10,20)
print(j[0], j[1], j[2])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(np.flip(j))

# 15- Üretilen matrisin ilk satırını seçiniz.
print(i[0,:])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(i[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(i[:, 0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(np.power(i, 2))

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
k = np.random.randint(-50, 50, size=(3, 3))
print(k)
l = k[(k > 0) & (k % 2 == 0)]
print(l)

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[12 12 28 15 24]
[-1.84842603 -1.13225383 -0.62368157 -0.122961   -0.6469147  -1.28892414
  1.08840798 -0.98692966 -2.68148994  1.04517122]
[[23 20 44 13 37]
 [30 39 37 41 38]
 [49 39 21 43 30]]
[102  98 102  97 105]
[137 185 182]
49
13
33.6
[2] [0]
10 11 12
[19 18 17 16 15 14 13 12 11 10]
[23 20 44 13 37]
37
[23 30 49]
[[ 529  400 1936  169 1369]
 [ 900 1521 1369 1681 1444]
 [2401 1521  441 1849  900]]
[[ -5  23  -8]
 [-25  30 -20]
 [-28  14 -38]]
[30 14]
