In [1]:
import pandas as pd
import numpy as np

In [2]:
l = [1,2,3,4,5]
pd.DataFrame(l, columns=["degisken_ismi"])

degisken_ismi
0              1
1              2
2              3
3              4
4              5

In [3]:
m = np.arange(1,10).reshape((3,3))
pd.DataFrame(m, columns=["1","2","3"])

1  2  3
0  1  2  3
1  4  5  6
2  7  8  9

In [6]:
df = pd.DataFrame(m, columns=["var1", "var2", "var3"])
df.head(2)

var1  var2  var3
0     1     2     3
1     4     5     6

In [8]:
df.columns = {"degisken1", "degisken2", "degisken3"}
df

degisken2  degisken1  degisken3
0          1          2          3
1          4          5          6
2          7          8          9

In [10]:
print(df.axes)
print(df.shape)
print(df.ndim)
print(df.size)
print(df.values)

[RangeIndex(start=0, stop=3, step=1), Index(['degisken2', 'degisken1', 'degisken3'], dtype='object')]
(3, 3)
2
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
df.tail(1)

degisken2  degisken1  degisken3
2          7          8          9