In [1]:
pip install numpy


  Using cached numpy-1.24.2-cp311-cp311-win_amd64.whl (14.8 MB)



[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
#klasik yöntem
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0,len(a)):
    ab.append(a[i]* b[i])

print(ab)

[2, 6, 12, 20]


In [1]:
#Numpy ile
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a*b) 

[ 2  6 12 20]


In [3]:
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(multi.shape)
print(x.shape)

(3, 3)
(9,)


In [8]:
print(x.ndim)
print(multi.ndim)

1
2


In [3]:
import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [7]:
a = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [8]:
print(np.concatenate([a,a], axis= 1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [10]:
m = np.array([1,2,3,99,99,3,2,1])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


In [11]:
a,b,c = np.split(m,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


In [12]:
n = np.arange(16).reshape(4,4)
np.vsplit(n,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [13]:
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [14]:
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.linspace(0,50,6)

array([ 0., 10., 20., 30., 40., 50.])

In [26]:
np.random.randint(0,10,3)

array([5, 0, 3])

In [28]:
npArray = np.arange(50)
npMulti = npArray.reshape(5,10)
print(npMulti.sum(axis = 1 ))

[ 45 145 245 345 445]


In [31]:
a = np.random.randint(10, size = 10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int32


In [32]:
v = np.array([8,24,232,12,5,42,55])
print(v)
v.sort()
print(v)

[  8  24 232  12   5  42  55]
[  5   8  12  24  42  55 232]


In [33]:
n = np.random.normal(20,5,(3,3))
print(n)

[[22.06646531 18.91730036 26.05492326]
 [22.99713332 26.53848454 22.90125656]
 [20.06358772 16.71985975 12.05958059]]


In [34]:
print(np.sort(n,axis=0))

[[20.06358772 16.71985975 12.05958059]
 [22.06646531 18.91730036 22.90125656]
 [22.99713332 26.53848454 26.05492326]]


In [35]:
print(np.sort(n,axis=1))

[[18.91730036 22.06646531 26.05492326]
 [22.90125656 22.99713332 26.53848454]
 [12.05958059 16.71985975 20.06358772]]


In [36]:
a = np.array([1,2,3,4,5])
print(a[0])
print(a[-1])
a[0] = 100
print(a[0])

1
5
100


In [38]:
a = np.random.randint(10, size=(3,5))
print(a)

[[1 1 3 6 6]
 [3 4 1 5 2]
 [0 3 9 2 0]]


In [39]:
print(a[0,0])

1


In [40]:
print(a[1,1])

4


In [44]:
a[1,4] = 100
print(a)

[[  1   1   3   6   6]
 [  3   4   1   5 100]
 [  0   3   9   2   0]]


In [46]:
a[2,4]=3.14
print(a)

[[  1   1   3   6   6]
 [  3   4   1   5 100]
 [  0   3   9   2   3]]
