In [2]:
import numpy as np

In [3]:
a = np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [4]:
print(a[0:3])

[20 21 22]


In [5]:
print(a[:3])

[20 21 22]


In [6]:
print(a[3:])

[23 24 25 26 27 28 29]


In [9]:
print(a[1::2])

[21 23 25 27 29]


In [10]:
print(a[0::2])

[20 22 24 26 28]


In [14]:
print(a[::-1])

[29 28 27 26 25 24 23 22 21 20]


In [15]:
b= np.random.randint(10,size=[5,5])

In [16]:
print(b)

[[0 8 3 2 4]
 [9 8 1 4 2]
 [7 6 2 3 8]
 [4 8 3 6 4]
 [4 1 5 3 7]]


In [17]:
print(b[:,0])

[0 9 7 4 4]


In [19]:
print(b[:,1])

[8 8 6 8 1]


In [20]:
print(b[0,:])

[0 8 3 2 4]


In [21]:
print(b[1,:])

[9 8 1 4 2]


In [22]:
print(b[0:2,0:3])

[[0 8 3]
 [9 8 1]]


In [23]:
print(b[::2,::2])

[[0 3 4]
 [7 2 8]
 [4 5 7]]


In [25]:
alt_B = b[0:3,0:2]
print(alt_B)

[[0 8]
 [9 8]
 [7 6]]


In [27]:
alt_B[0,0] = 100
alt_B[1,1] = 200
print(b)
print(alt_B)

[[100   8   3   2   4]
 [  9 200   1   4   2]
 [  7   6   2   3   8]
 [  4   8   3   6   4]
 [  4   1   5   3   7]]
[[100   8]
 [  9 200]
 [  7   6]]


In [28]:
v = np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [29]:
yetgen = [1,3,5]
print(v[yetgen])

[ 3  9 15]


In [31]:
n = np.arange(9).reshape(3,3)
satir= np.array([0,1])
sutun = np.array([1,2])
print(n[satir,sutun])

[1 5]


In [32]:
v = np.array([1,2,3,4,5])
print(v>3)

[False False False  True  True]


In [33]:
print(v[v>3])

[4 5]


In [36]:
print(v[v<=3])

[1 2 3]


In [37]:
print(v[v!=3])

[1 2 4 5]


In [38]:
print(v[v==3])

[3]


In [39]:
print(v*2)

[ 2  4  6  8 10]


In [40]:
print(v+2)

[3 4 5 6 7]


In [41]:
print(v/2)

[0.5 1.  1.5 2.  2.5]


In [42]:
print(v-1)

[0 1 2 3 4]


In [43]:
print(np.subtract(v,3))

[-2 -1  0  1  2]


In [44]:
print(np.add(v,2))

[3 4 5 6 7]


In [45]:
np.multiply(v,2)

array([ 2,  4,  6,  8, 10])

In [46]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [47]:
np.power(v,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [48]:
np.mod(v,5)

array([1, 2, 3, 4, 0], dtype=int32)

In [49]:
print(np.absolute(v)) #mutlak değer

[1 2 3 4 5]


In [50]:
print(np.sin(360))

0.9589157234143065


In [51]:
np.log(10)

2.302585092994046

In [53]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])
x = np.linalg.solve(a,b)
print(x)

[1.85714286 2.71428571]
